apiVersion: v1
kind: Service
metadata:
  name: ev-share-predictor-service
spec:
  type: LoadBalancer
  selector:
    app: ev-share-predictor-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007