name: Continuous Deployment to Minikube on GCP VM

on:
  push:
    branches:
      - Dev
      - Prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate model.pkl
      run: python3 model.py

    - name: Run basic tests before deploy
      run: python3 -m unittest discover tests

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

    - name: Install gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ultra-complex-453410-t3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/ev-share-predictor
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)

        docker build -t $IMAGE_NAME:latest \
                     -t $IMAGE_NAME:${{ github.ref_name }} \
                     -t $IMAGE_NAME:${{ github.ref_name }}-$SHORT_SHA .

        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.ref_name }}
        docker push $IMAGE_NAME:${{ github.ref_name }}-$SHORT_SHA

    - name: SSH into GCP VM and deploy to Minikube
      run: |
        gcloud compute ssh testosteroneig@docker-practical1 --zone=europe-west4-b --command="
        cd /home/testosteroneig && \
        rm -rf ev-share-predictor-mlops && \
        git clone https://github.com/7arhan1/ev-share-predictor-mlops.git && \
        cd ev-share-predictor-mlops && \
        ls -l && \
        python3 model.py && \
        cd minikube_services && \
        ls -l && \
        /usr/local/bin/minikube kubectl -- delete -f ./deployment.yml || true && \
        sleep 5 && \
        /usr/local/bin/minikube kubectl -- apply -f ./deployment.yml"