name: Continuous Integration Building + Testing

on:
  push:
    branches: [Dev, Features]
  pull_request:
    branches: [Dev, Features]

    branches: [dev, features]
  pull_request:
    branches: [dev, features]
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Unit and Integration Tests
      run: |
        python -m unittest discover -s tests

